### ISSUE TITLE
[Feature requests] option to show translated text as mini popup?

### ISSUE THREAD

**Issue by rieje** [xpmn/firefox-to-deepl#17]
Three simple feature requests:

* Option to show translated text as mini popup above highlighted text instead of tab. Opening as a tab breaks the flow of reading the webpage and people using this addon only wants part of the webpage translated (likely just a word, a sentence, or a short paragraph).

* When pressing mouse button to highlight text, on release show mini popup of translation or the option to click a DeepL icon to translate. Beats hunting it in the context menu.

* Option to translate the entire page "in-line" and/or in a separate tab.

I wouldn't be surprised if none of these requests are possible to implement as a Firefox extension but I'm curious on your thoughts.

**Comment by xpmn** [comment]
Simple popup solution was implemented by @kaermorchen
Thanks to him - this issue is closed
