### ISSUE TITLE
Latest DeepL update broke plugin

### ISSUE THREAD

**Issue by Hakkin** [xpmn/firefox-to-deepl#21]
It seems like the latest DeepL update broke the `deepl.com/translator#null` link format the plugin uses, it just opens a blank page now.

It seems you can do a similar thing using the link format `deepl.com/translator/q/auto/text/en`, where `text` and `en` are the source text and target language.

**Comment by xpmn** [comment]
Thank you for noticing, Fixed

**Comment by Hakkin** [comment]
Thank you!

**Comment by Hakkin** [comment]
Actually, it seems like that new link style doesn't work with text containing newline characters (%0A). It fixed it for basic single line text but it's still broken for multi-line text.

**Comment by xpmn** [comment]
It looks like that DeepL text in URL is now not encoding any of the symbols, like \ | / \n 
Don't know what to do. Can just replace them to space, but it is looks bad

**Comment by Hakkin** [comment]
I just tested again and it seems like the original `deepl.com/translator#null` URL is working again...odd. Seems like you may just be able to revert the change for now if it's also working for you?

**Comment by xpmn** [comment]
Reverted all back, lol

Nice work, everybody :D
