### ISSUE TITLE
Trying to translate multiline text opens a 404 page

### ISSUE THREAD

**Issue by literal-line** [xpmn/firefox-to-deepl#22]
If I try to translate some text that contains line breaks, the DeepL window shows a 404 page.

![image](https://user-images.githubusercontent.com/13988479/202918891-e79b3a7f-6d4b-4b1a-9f9d-d48304de54e6.png)

**Comment by xpmn** [comment]
Hi, have you tried to update extension? This was an issue with changed url: #21 
Should work now

**Comment by xpmn** [comment]
I believe that this is fixed now

**Comment by literal-line** [comment]
Yup, it's all good now
