### ISSUE TITLE
Use floating button instead of right click menu?

### ISSUE THREAD

**Issue by gcobc12632** [xpmn/firefox-to-deepl#27]
Just like this:
https://addons.mozilla.org/firefox/addon/simple-translate

When you select text, a floating button will appear.

After clicking, the DeepL pop-up window will be displayed.

Is this possible?

**Comment by xpmn** [comment]
Hi, thank you for your feedback, but I wanted to create extension with as minimum requirements as possible - this tiny popup is implemented by injecting fixed html block on top of the page content. For this I need to add permission "Access your data for all websites" which looks not so trustworthy for not verified extension. And in the next manifest v3 it will not be possible to set this permission. 
I decided to not implement this

**Comment by gcobc12632** [comment]
I don't mean to be exactly like that addons.

I mean, when you select text. Show a floating button.
![](https://user-images.githubusercontent.com/31128599/220088604-4c3448ba-036a-4d6c-b9b4-df74bc551869.png)

When you click it, show a DeepL pop-up window. (what you already have)
![](https://user-images.githubusercontent.com/31128599/220088102-a00dec82-b03f-463b-9d84-844c5183a41c.png)

That's it.
Is this also requires permission "Access your data for all websites"?

There is such an idea mainly because.
The way it is now, you have to right-click first and then select the "To DeepL" option.
It takes a total of two clicks.
The floating button only needs to be clicked once.

If there is no way, it does not matter.
This extension is already very good.

**Comment by xpmn** [comment]
Yes this also requires permission "Access your data for all websites" because there is no possibility to render popup icon with browser API. This is imitation with injecting floating block just inside of the page html
